//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techfix.QuotationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuotationIDField;
        
        private int RFQIDField;
        
        private int SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        private decimal QuotationAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuotationDetailsField;
        
        private System.DateTime SubmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((this.QuotationIDField.Equals(value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RFQID {
            get {
                return this.RFQIDField;
            }
            set {
                if ((this.RFQIDField.Equals(value) != true)) {
                    this.RFQIDField = value;
                    this.RaisePropertyChanged("RFQID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal QuotationAmount {
            get {
                return this.QuotationAmountField;
            }
            set {
                if ((this.QuotationAmountField.Equals(value) != true)) {
                    this.QuotationAmountField = value;
                    this.RaisePropertyChanged("QuotationAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DeliverySchedule {
            get {
                return this.DeliveryScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryScheduleField, value) != true)) {
                    this.DeliveryScheduleField = value;
                    this.RaisePropertyChanged("DeliverySchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string QuotationDetails {
            get {
                return this.QuotationDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuotationDetailsField, value) != true)) {
                    this.QuotationDetailsField = value;
                    this.RaisePropertyChanged("QuotationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime SubmissionDate {
            get {
                return this.SubmissionDateField;
            }
            set {
                if ((this.SubmissionDateField.Equals(value) != true)) {
                    this.SubmissionDateField = value;
                    this.RaisePropertyChanged("SubmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuotationService.QuotationServiceSoap")]
    public interface QuotationServiceSoap {
        
        // CODEGEN: Generating message contract since element name deliverySchedule from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitQuotation", ReplyAction="*")]
        Techfix.QuotationService.SubmitQuotationResponse SubmitQuotation(Techfix.QuotationService.SubmitQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitQuotation", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.QuotationService.SubmitQuotationResponse> SubmitQuotationAsync(Techfix.QuotationService.SubmitQuotationRequest request);
        
        // CODEGEN: Generating message contract since element name AcceptQuotationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptQuotation", ReplyAction="*")]
        Techfix.QuotationService.AcceptQuotationResponse AcceptQuotation(Techfix.QuotationService.AcceptQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptQuotation", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.QuotationService.AcceptQuotationResponse> AcceptQuotationAsync(Techfix.QuotationService.AcceptQuotationRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuotationsByRFQIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuotationsByRFQID", ReplyAction="*")]
        Techfix.QuotationService.GetQuotationsByRFQIDResponse GetQuotationsByRFQID(Techfix.QuotationService.GetQuotationsByRFQIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuotationsByRFQID", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.QuotationService.GetQuotationsByRFQIDResponse> GetQuotationsByRFQIDAsync(Techfix.QuotationService.GetQuotationsByRFQIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitQuotationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitQuotation", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.SubmitQuotationRequestBody Body;
        
        public SubmitQuotationRequest() {
        }
        
        public SubmitQuotationRequest(Techfix.QuotationService.SubmitQuotationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitQuotationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rfqID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal quotationAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string deliverySchedule;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string quotationDetails;
        
        public SubmitQuotationRequestBody() {
        }
        
        public SubmitQuotationRequestBody(int rfqID, int supplierID, decimal quotationAmount, string deliverySchedule, string quotationDetails) {
            this.rfqID = rfqID;
            this.supplierID = supplierID;
            this.quotationAmount = quotationAmount;
            this.deliverySchedule = deliverySchedule;
            this.quotationDetails = quotationDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitQuotationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitQuotationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.SubmitQuotationResponseBody Body;
        
        public SubmitQuotationResponse() {
        }
        
        public SubmitQuotationResponse(Techfix.QuotationService.SubmitQuotationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitQuotationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitQuotationResult;
        
        public SubmitQuotationResponseBody() {
        }
        
        public SubmitQuotationResponseBody(string SubmitQuotationResult) {
            this.SubmitQuotationResult = SubmitQuotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptQuotationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptQuotation", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.AcceptQuotationRequestBody Body;
        
        public AcceptQuotationRequest() {
        }
        
        public AcceptQuotationRequest(Techfix.QuotationService.AcceptQuotationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AcceptQuotationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int quotationID;
        
        public AcceptQuotationRequestBody() {
        }
        
        public AcceptQuotationRequestBody(int quotationID) {
            this.quotationID = quotationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptQuotationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptQuotationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.AcceptQuotationResponseBody Body;
        
        public AcceptQuotationResponse() {
        }
        
        public AcceptQuotationResponse(Techfix.QuotationService.AcceptQuotationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AcceptQuotationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcceptQuotationResult;
        
        public AcceptQuotationResponseBody() {
        }
        
        public AcceptQuotationResponseBody(string AcceptQuotationResult) {
            this.AcceptQuotationResult = AcceptQuotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuotationsByRFQIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuotationsByRFQID", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.GetQuotationsByRFQIDRequestBody Body;
        
        public GetQuotationsByRFQIDRequest() {
        }
        
        public GetQuotationsByRFQIDRequest(Techfix.QuotationService.GetQuotationsByRFQIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuotationsByRFQIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rfqID;
        
        public GetQuotationsByRFQIDRequestBody() {
        }
        
        public GetQuotationsByRFQIDRequestBody(int rfqID) {
            this.rfqID = rfqID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuotationsByRFQIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuotationsByRFQIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.QuotationService.GetQuotationsByRFQIDResponseBody Body;
        
        public GetQuotationsByRFQIDResponse() {
        }
        
        public GetQuotationsByRFQIDResponse(Techfix.QuotationService.GetQuotationsByRFQIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuotationsByRFQIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.QuotationService.Quotation[] GetQuotationsByRFQIDResult;
        
        public GetQuotationsByRFQIDResponseBody() {
        }
        
        public GetQuotationsByRFQIDResponseBody(Techfix.QuotationService.Quotation[] GetQuotationsByRFQIDResult) {
            this.GetQuotationsByRFQIDResult = GetQuotationsByRFQIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuotationServiceSoapChannel : Techfix.QuotationService.QuotationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotationServiceSoapClient : System.ServiceModel.ClientBase<Techfix.QuotationService.QuotationServiceSoap>, Techfix.QuotationService.QuotationServiceSoap {
        
        public QuotationServiceSoapClient() {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.QuotationService.SubmitQuotationResponse Techfix.QuotationService.QuotationServiceSoap.SubmitQuotation(Techfix.QuotationService.SubmitQuotationRequest request) {
            return base.Channel.SubmitQuotation(request);
        }
        
        public string SubmitQuotation(int rfqID, int supplierID, decimal quotationAmount, string deliverySchedule, string quotationDetails) {
            Techfix.QuotationService.SubmitQuotationRequest inValue = new Techfix.QuotationService.SubmitQuotationRequest();
            inValue.Body = new Techfix.QuotationService.SubmitQuotationRequestBody();
            inValue.Body.rfqID = rfqID;
            inValue.Body.supplierID = supplierID;
            inValue.Body.quotationAmount = quotationAmount;
            inValue.Body.deliverySchedule = deliverySchedule;
            inValue.Body.quotationDetails = quotationDetails;
            Techfix.QuotationService.SubmitQuotationResponse retVal = ((Techfix.QuotationService.QuotationServiceSoap)(this)).SubmitQuotation(inValue);
            return retVal.Body.SubmitQuotationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.QuotationService.SubmitQuotationResponse> Techfix.QuotationService.QuotationServiceSoap.SubmitQuotationAsync(Techfix.QuotationService.SubmitQuotationRequest request) {
            return base.Channel.SubmitQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.QuotationService.SubmitQuotationResponse> SubmitQuotationAsync(int rfqID, int supplierID, decimal quotationAmount, string deliverySchedule, string quotationDetails) {
            Techfix.QuotationService.SubmitQuotationRequest inValue = new Techfix.QuotationService.SubmitQuotationRequest();
            inValue.Body = new Techfix.QuotationService.SubmitQuotationRequestBody();
            inValue.Body.rfqID = rfqID;
            inValue.Body.supplierID = supplierID;
            inValue.Body.quotationAmount = quotationAmount;
            inValue.Body.deliverySchedule = deliverySchedule;
            inValue.Body.quotationDetails = quotationDetails;
            return ((Techfix.QuotationService.QuotationServiceSoap)(this)).SubmitQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.QuotationService.AcceptQuotationResponse Techfix.QuotationService.QuotationServiceSoap.AcceptQuotation(Techfix.QuotationService.AcceptQuotationRequest request) {
            return base.Channel.AcceptQuotation(request);
        }
        
        public string AcceptQuotation(int quotationID) {
            Techfix.QuotationService.AcceptQuotationRequest inValue = new Techfix.QuotationService.AcceptQuotationRequest();
            inValue.Body = new Techfix.QuotationService.AcceptQuotationRequestBody();
            inValue.Body.quotationID = quotationID;
            Techfix.QuotationService.AcceptQuotationResponse retVal = ((Techfix.QuotationService.QuotationServiceSoap)(this)).AcceptQuotation(inValue);
            return retVal.Body.AcceptQuotationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.QuotationService.AcceptQuotationResponse> Techfix.QuotationService.QuotationServiceSoap.AcceptQuotationAsync(Techfix.QuotationService.AcceptQuotationRequest request) {
            return base.Channel.AcceptQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.QuotationService.AcceptQuotationResponse> AcceptQuotationAsync(int quotationID) {
            Techfix.QuotationService.AcceptQuotationRequest inValue = new Techfix.QuotationService.AcceptQuotationRequest();
            inValue.Body = new Techfix.QuotationService.AcceptQuotationRequestBody();
            inValue.Body.quotationID = quotationID;
            return ((Techfix.QuotationService.QuotationServiceSoap)(this)).AcceptQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.QuotationService.GetQuotationsByRFQIDResponse Techfix.QuotationService.QuotationServiceSoap.GetQuotationsByRFQID(Techfix.QuotationService.GetQuotationsByRFQIDRequest request) {
            return base.Channel.GetQuotationsByRFQID(request);
        }
        
        public Techfix.QuotationService.Quotation[] GetQuotationsByRFQID(int rfqID) {
            Techfix.QuotationService.GetQuotationsByRFQIDRequest inValue = new Techfix.QuotationService.GetQuotationsByRFQIDRequest();
            inValue.Body = new Techfix.QuotationService.GetQuotationsByRFQIDRequestBody();
            inValue.Body.rfqID = rfqID;
            Techfix.QuotationService.GetQuotationsByRFQIDResponse retVal = ((Techfix.QuotationService.QuotationServiceSoap)(this)).GetQuotationsByRFQID(inValue);
            return retVal.Body.GetQuotationsByRFQIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.QuotationService.GetQuotationsByRFQIDResponse> Techfix.QuotationService.QuotationServiceSoap.GetQuotationsByRFQIDAsync(Techfix.QuotationService.GetQuotationsByRFQIDRequest request) {
            return base.Channel.GetQuotationsByRFQIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.QuotationService.GetQuotationsByRFQIDResponse> GetQuotationsByRFQIDAsync(int rfqID) {
            Techfix.QuotationService.GetQuotationsByRFQIDRequest inValue = new Techfix.QuotationService.GetQuotationsByRFQIDRequest();
            inValue.Body = new Techfix.QuotationService.GetQuotationsByRFQIDRequestBody();
            inValue.Body.rfqID = rfqID;
            return ((Techfix.QuotationService.QuotationServiceSoap)(this)).GetQuotationsByRFQIDAsync(inValue);
        }
    }
}
