//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techfix.ProcurementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcurementService.ProcurementServiceSoap")]
    public interface ProcurementServiceSoap {
        
        // CODEGEN: Generating message contract since element name productDescription from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitRFQ", ReplyAction="*")]
        Techfix.ProcurementService.SubmitRFQResponse SubmitRFQ(Techfix.ProcurementService.SubmitRFQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitRFQ", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.ProcurementService.SubmitRFQResponse> SubmitRFQAsync(Techfix.ProcurementService.SubmitRFQRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRFQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitRFQ", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.ProcurementService.SubmitRFQRequestBody Body;
        
        public SubmitRFQRequest() {
        }
        
        public SubmitRFQRequest(Techfix.ProcurementService.SubmitRFQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitRFQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string specifications;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string deliveryRequirements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pricingFormat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string paymentTerms;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime validityPeriod;
        
        public SubmitRFQRequestBody() {
        }
        
        public SubmitRFQRequestBody(string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            this.productDescription = productDescription;
            this.quantity = quantity;
            this.specifications = specifications;
            this.deliveryRequirements = deliveryRequirements;
            this.pricingFormat = pricingFormat;
            this.paymentTerms = paymentTerms;
            this.validityPeriod = validityPeriod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRFQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitRFQResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.ProcurementService.SubmitRFQResponseBody Body;
        
        public SubmitRFQResponse() {
        }
        
        public SubmitRFQResponse(Techfix.ProcurementService.SubmitRFQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitRFQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitRFQResult;
        
        public SubmitRFQResponseBody() {
        }
        
        public SubmitRFQResponseBody(string SubmitRFQResult) {
            this.SubmitRFQResult = SubmitRFQResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcurementServiceSoapChannel : Techfix.ProcurementService.ProcurementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcurementServiceSoapClient : System.ServiceModel.ClientBase<Techfix.ProcurementService.ProcurementServiceSoap>, Techfix.ProcurementService.ProcurementServiceSoap {
        
        public ProcurementServiceSoapClient() {
        }
        
        public ProcurementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcurementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcurementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcurementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.ProcurementService.SubmitRFQResponse Techfix.ProcurementService.ProcurementServiceSoap.SubmitRFQ(Techfix.ProcurementService.SubmitRFQRequest request) {
            return base.Channel.SubmitRFQ(request);
        }
        
        public string SubmitRFQ(string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            Techfix.ProcurementService.SubmitRFQRequest inValue = new Techfix.ProcurementService.SubmitRFQRequest();
            inValue.Body = new Techfix.ProcurementService.SubmitRFQRequestBody();
            inValue.Body.productDescription = productDescription;
            inValue.Body.quantity = quantity;
            inValue.Body.specifications = specifications;
            inValue.Body.deliveryRequirements = deliveryRequirements;
            inValue.Body.pricingFormat = pricingFormat;
            inValue.Body.paymentTerms = paymentTerms;
            inValue.Body.validityPeriod = validityPeriod;
            Techfix.ProcurementService.SubmitRFQResponse retVal = ((Techfix.ProcurementService.ProcurementServiceSoap)(this)).SubmitRFQ(inValue);
            return retVal.Body.SubmitRFQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.ProcurementService.SubmitRFQResponse> Techfix.ProcurementService.ProcurementServiceSoap.SubmitRFQAsync(Techfix.ProcurementService.SubmitRFQRequest request) {
            return base.Channel.SubmitRFQAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.ProcurementService.SubmitRFQResponse> SubmitRFQAsync(string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            Techfix.ProcurementService.SubmitRFQRequest inValue = new Techfix.ProcurementService.SubmitRFQRequest();
            inValue.Body = new Techfix.ProcurementService.SubmitRFQRequestBody();
            inValue.Body.productDescription = productDescription;
            inValue.Body.quantity = quantity;
            inValue.Body.specifications = specifications;
            inValue.Body.deliveryRequirements = deliveryRequirements;
            inValue.Body.pricingFormat = pricingFormat;
            inValue.Body.paymentTerms = paymentTerms;
            inValue.Body.validityPeriod = validityPeriod;
            return ((Techfix.ProcurementService.ProcurementServiceSoap)(this)).SubmitRFQAsync(inValue);
        }
    }
}
