//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techfix.SupplierService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SupplierModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessNameField;
        
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BusinessName {
            get {
                return this.BusinessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessNameField, value) != true)) {
                    this.BusinessNameField = value;
                    this.RaisePropertyChanged("BusinessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierService.SupplierServiceSoap")]
    public interface SupplierServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        Techfix.SupplierService.AddSupplierResponse AddSupplier(Techfix.SupplierService.AddSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.SupplierService.AddSupplierResponse> AddSupplierAsync(Techfix.SupplierService.AddSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSuppliersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        Techfix.SupplierService.GetAllSuppliersResponse GetAllSuppliers(Techfix.SupplierService.GetAllSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.SupplierService.GetAllSuppliersResponse> GetAllSuppliersAsync(Techfix.SupplierService.GetAllSuppliersRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        Techfix.SupplierService.UpdateSupplierResponse UpdateSupplier(Techfix.SupplierService.UpdateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.SupplierService.UpdateSupplierResponse> UpdateSupplierAsync(Techfix.SupplierService.UpdateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSupplierStatus", ReplyAction="*")]
        bool SetSupplierStatus(int supplierID, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSupplierStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetSupplierStatusAsync(int supplierID, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        bool DeleteSupplier(int supplierID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteSupplierAsync(int supplierID);
        
        // CODEGEN: Generating message contract since element name GetSupplierByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierByID", ReplyAction="*")]
        Techfix.SupplierService.GetSupplierByIDResponse GetSupplierByID(Techfix.SupplierService.GetSupplierByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.SupplierService.GetSupplierByIDResponse> GetSupplierByIDAsync(Techfix.SupplierService.GetSupplierByIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.AddSupplierRequestBody Body;
        
        public AddSupplierRequest() {
        }
        
        public AddSupplierRequest(Techfix.SupplierService.AddSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string businessName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool isActive;
        
        public AddSupplierRequestBody() {
        }
        
        public AddSupplierRequestBody(string name, string email, string username, string password, string phone, string address, string businessName, bool isActive) {
            this.name = name;
            this.email = email;
            this.username = username;
            this.password = password;
            this.phone = phone;
            this.address = address;
            this.businessName = businessName;
            this.isActive = isActive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.AddSupplierResponseBody Body;
        
        public AddSupplierResponse() {
        }
        
        public AddSupplierResponse(Techfix.SupplierService.AddSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSupplierResult;
        
        public AddSupplierResponseBody() {
        }
        
        public AddSupplierResponseBody(bool AddSupplierResult) {
            this.AddSupplierResult = AddSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.GetAllSuppliersRequestBody Body;
        
        public GetAllSuppliersRequest() {
        }
        
        public GetAllSuppliersRequest(Techfix.SupplierService.GetAllSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSuppliersRequestBody {
        
        public GetAllSuppliersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.GetAllSuppliersResponseBody Body;
        
        public GetAllSuppliersResponse() {
        }
        
        public GetAllSuppliersResponse(Techfix.SupplierService.GetAllSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.SupplierService.SupplierModel[] GetAllSuppliersResult;
        
        public GetAllSuppliersResponseBody() {
        }
        
        public GetAllSuppliersResponseBody(Techfix.SupplierService.SupplierModel[] GetAllSuppliersResult) {
            this.GetAllSuppliersResult = GetAllSuppliersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.UpdateSupplierRequestBody Body;
        
        public UpdateSupplierRequest() {
        }
        
        public UpdateSupplierRequest(Techfix.SupplierService.UpdateSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string businessName;
        
        public UpdateSupplierRequestBody() {
        }
        
        public UpdateSupplierRequestBody(int supplierID, string name, string username, string password, string email, string phone, string address, string businessName) {
            this.supplierID = supplierID;
            this.name = name;
            this.username = username;
            this.password = password;
            this.email = email;
            this.phone = phone;
            this.address = address;
            this.businessName = businessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.UpdateSupplierResponseBody Body;
        
        public UpdateSupplierResponse() {
        }
        
        public UpdateSupplierResponse(Techfix.SupplierService.UpdateSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateSupplierResult;
        
        public UpdateSupplierResponseBody() {
        }
        
        public UpdateSupplierResponseBody(bool UpdateSupplierResult) {
            this.UpdateSupplierResult = UpdateSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupplierByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupplierByID", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.GetSupplierByIDRequestBody Body;
        
        public GetSupplierByIDRequest() {
        }
        
        public GetSupplierByIDRequest(Techfix.SupplierService.GetSupplierByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSupplierByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierID;
        
        public GetSupplierByIDRequestBody() {
        }
        
        public GetSupplierByIDRequestBody(int supplierID) {
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupplierByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupplierByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.SupplierService.GetSupplierByIDResponseBody Body;
        
        public GetSupplierByIDResponse() {
        }
        
        public GetSupplierByIDResponse(Techfix.SupplierService.GetSupplierByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSupplierByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.SupplierService.SupplierModel GetSupplierByIDResult;
        
        public GetSupplierByIDResponseBody() {
        }
        
        public GetSupplierByIDResponseBody(Techfix.SupplierService.SupplierModel GetSupplierByIDResult) {
            this.GetSupplierByIDResult = GetSupplierByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierServiceSoapChannel : Techfix.SupplierService.SupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceSoapClient : System.ServiceModel.ClientBase<Techfix.SupplierService.SupplierServiceSoap>, Techfix.SupplierService.SupplierServiceSoap {
        
        public SupplierServiceSoapClient() {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.SupplierService.AddSupplierResponse Techfix.SupplierService.SupplierServiceSoap.AddSupplier(Techfix.SupplierService.AddSupplierRequest request) {
            return base.Channel.AddSupplier(request);
        }
        
        public bool AddSupplier(string name, string email, string username, string password, string phone, string address, string businessName, bool isActive) {
            Techfix.SupplierService.AddSupplierRequest inValue = new Techfix.SupplierService.AddSupplierRequest();
            inValue.Body = new Techfix.SupplierService.AddSupplierRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.phone = phone;
            inValue.Body.address = address;
            inValue.Body.businessName = businessName;
            inValue.Body.isActive = isActive;
            Techfix.SupplierService.AddSupplierResponse retVal = ((Techfix.SupplierService.SupplierServiceSoap)(this)).AddSupplier(inValue);
            return retVal.Body.AddSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.SupplierService.AddSupplierResponse> Techfix.SupplierService.SupplierServiceSoap.AddSupplierAsync(Techfix.SupplierService.AddSupplierRequest request) {
            return base.Channel.AddSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.SupplierService.AddSupplierResponse> AddSupplierAsync(string name, string email, string username, string password, string phone, string address, string businessName, bool isActive) {
            Techfix.SupplierService.AddSupplierRequest inValue = new Techfix.SupplierService.AddSupplierRequest();
            inValue.Body = new Techfix.SupplierService.AddSupplierRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.phone = phone;
            inValue.Body.address = address;
            inValue.Body.businessName = businessName;
            inValue.Body.isActive = isActive;
            return ((Techfix.SupplierService.SupplierServiceSoap)(this)).AddSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.SupplierService.GetAllSuppliersResponse Techfix.SupplierService.SupplierServiceSoap.GetAllSuppliers(Techfix.SupplierService.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliers(request);
        }
        
        public Techfix.SupplierService.SupplierModel[] GetAllSuppliers() {
            Techfix.SupplierService.GetAllSuppliersRequest inValue = new Techfix.SupplierService.GetAllSuppliersRequest();
            inValue.Body = new Techfix.SupplierService.GetAllSuppliersRequestBody();
            Techfix.SupplierService.GetAllSuppliersResponse retVal = ((Techfix.SupplierService.SupplierServiceSoap)(this)).GetAllSuppliers(inValue);
            return retVal.Body.GetAllSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.SupplierService.GetAllSuppliersResponse> Techfix.SupplierService.SupplierServiceSoap.GetAllSuppliersAsync(Techfix.SupplierService.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.SupplierService.GetAllSuppliersResponse> GetAllSuppliersAsync() {
            Techfix.SupplierService.GetAllSuppliersRequest inValue = new Techfix.SupplierService.GetAllSuppliersRequest();
            inValue.Body = new Techfix.SupplierService.GetAllSuppliersRequestBody();
            return ((Techfix.SupplierService.SupplierServiceSoap)(this)).GetAllSuppliersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.SupplierService.UpdateSupplierResponse Techfix.SupplierService.SupplierServiceSoap.UpdateSupplier(Techfix.SupplierService.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplier(request);
        }
        
        public bool UpdateSupplier(int supplierID, string name, string username, string password, string email, string phone, string address, string businessName) {
            Techfix.SupplierService.UpdateSupplierRequest inValue = new Techfix.SupplierService.UpdateSupplierRequest();
            inValue.Body = new Techfix.SupplierService.UpdateSupplierRequestBody();
            inValue.Body.supplierID = supplierID;
            inValue.Body.name = name;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.address = address;
            inValue.Body.businessName = businessName;
            Techfix.SupplierService.UpdateSupplierResponse retVal = ((Techfix.SupplierService.SupplierServiceSoap)(this)).UpdateSupplier(inValue);
            return retVal.Body.UpdateSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.SupplierService.UpdateSupplierResponse> Techfix.SupplierService.SupplierServiceSoap.UpdateSupplierAsync(Techfix.SupplierService.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.SupplierService.UpdateSupplierResponse> UpdateSupplierAsync(int supplierID, string name, string username, string password, string email, string phone, string address, string businessName) {
            Techfix.SupplierService.UpdateSupplierRequest inValue = new Techfix.SupplierService.UpdateSupplierRequest();
            inValue.Body = new Techfix.SupplierService.UpdateSupplierRequestBody();
            inValue.Body.supplierID = supplierID;
            inValue.Body.name = name;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.address = address;
            inValue.Body.businessName = businessName;
            return ((Techfix.SupplierService.SupplierServiceSoap)(this)).UpdateSupplierAsync(inValue);
        }
        
        public bool SetSupplierStatus(int supplierID, bool isActive) {
            return base.Channel.SetSupplierStatus(supplierID, isActive);
        }
        
        public System.Threading.Tasks.Task<bool> SetSupplierStatusAsync(int supplierID, bool isActive) {
            return base.Channel.SetSupplierStatusAsync(supplierID, isActive);
        }
        
        public bool DeleteSupplier(int supplierID) {
            return base.Channel.DeleteSupplier(supplierID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupplierAsync(int supplierID) {
            return base.Channel.DeleteSupplierAsync(supplierID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.SupplierService.GetSupplierByIDResponse Techfix.SupplierService.SupplierServiceSoap.GetSupplierByID(Techfix.SupplierService.GetSupplierByIDRequest request) {
            return base.Channel.GetSupplierByID(request);
        }
        
        public Techfix.SupplierService.SupplierModel GetSupplierByID(int supplierID) {
            Techfix.SupplierService.GetSupplierByIDRequest inValue = new Techfix.SupplierService.GetSupplierByIDRequest();
            inValue.Body = new Techfix.SupplierService.GetSupplierByIDRequestBody();
            inValue.Body.supplierID = supplierID;
            Techfix.SupplierService.GetSupplierByIDResponse retVal = ((Techfix.SupplierService.SupplierServiceSoap)(this)).GetSupplierByID(inValue);
            return retVal.Body.GetSupplierByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.SupplierService.GetSupplierByIDResponse> Techfix.SupplierService.SupplierServiceSoap.GetSupplierByIDAsync(Techfix.SupplierService.GetSupplierByIDRequest request) {
            return base.Channel.GetSupplierByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.SupplierService.GetSupplierByIDResponse> GetSupplierByIDAsync(int supplierID) {
            Techfix.SupplierService.GetSupplierByIDRequest inValue = new Techfix.SupplierService.GetSupplierByIDRequest();
            inValue.Body = new Techfix.SupplierService.GetSupplierByIDRequestBody();
            inValue.Body.supplierID = supplierID;
            return ((Techfix.SupplierService.SupplierServiceSoap)(this)).GetSupplierByIDAsync(inValue);
        }
    }
}
