//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techfix.DeliveryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryService.DeliveryServiceSoap")]
    public interface DeliveryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddDelivery(int purchaseOrderID, string shippingConfirmation, System.DateTime estimatedDeliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddDeliveryAsync(int purchaseOrderID, string shippingConfirmation, System.DateTime estimatedDeliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDeliveryStatus(int deliveryID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateDeliveryStatusAsync(int deliveryID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateActualDeliveryDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateActualDeliveryDate(int deliveryID, System.DateTime actualDeliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateActualDeliveryDate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateActualDeliveryDateAsync(int deliveryID, System.DateTime actualDeliveryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryWithProductInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDeliveryWithProductInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryWithProductInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDeliveryWithProductInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReturnDelivery(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReturnDeliveryAsync(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelDelivery(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CancelDeliveryAsync(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDeliveryDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllDeliveryDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDeliveryDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllDeliveryDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryDetailsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDeliveryDetailsByID(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryDetailsByID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDeliveryDetailsByIDAsync(int deliveryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchaseOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePurchaseOrderStatus(int purchaseOrderID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchaseOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePurchaseOrderStatusAsync(int purchaseOrderID, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeliveryServiceSoapChannel : Techfix.DeliveryService.DeliveryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryServiceSoapClient : System.ServiceModel.ClientBase<Techfix.DeliveryService.DeliveryServiceSoap>, Techfix.DeliveryService.DeliveryServiceSoap {
        
        public DeliveryServiceSoapClient() {
        }
        
        public DeliveryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddDelivery(int purchaseOrderID, string shippingConfirmation, System.DateTime estimatedDeliveryDate) {
            return base.Channel.AddDelivery(purchaseOrderID, shippingConfirmation, estimatedDeliveryDate);
        }
        
        public System.Threading.Tasks.Task<string> AddDeliveryAsync(int purchaseOrderID, string shippingConfirmation, System.DateTime estimatedDeliveryDate) {
            return base.Channel.AddDeliveryAsync(purchaseOrderID, shippingConfirmation, estimatedDeliveryDate);
        }
        
        public string UpdateDeliveryStatus(int deliveryID, string status) {
            return base.Channel.UpdateDeliveryStatus(deliveryID, status);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDeliveryStatusAsync(int deliveryID, string status) {
            return base.Channel.UpdateDeliveryStatusAsync(deliveryID, status);
        }
        
        public string UpdateActualDeliveryDate(int deliveryID, System.DateTime actualDeliveryDate) {
            return base.Channel.UpdateActualDeliveryDate(deliveryID, actualDeliveryDate);
        }
        
        public System.Threading.Tasks.Task<string> UpdateActualDeliveryDateAsync(int deliveryID, System.DateTime actualDeliveryDate) {
            return base.Channel.UpdateActualDeliveryDateAsync(deliveryID, actualDeliveryDate);
        }
        
        public System.Data.DataTable GetDeliveryWithProductInfo() {
            return base.Channel.GetDeliveryWithProductInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDeliveryWithProductInfoAsync() {
            return base.Channel.GetDeliveryWithProductInfoAsync();
        }
        
        public string ReturnDelivery(int deliveryID) {
            return base.Channel.ReturnDelivery(deliveryID);
        }
        
        public System.Threading.Tasks.Task<string> ReturnDeliveryAsync(int deliveryID) {
            return base.Channel.ReturnDeliveryAsync(deliveryID);
        }
        
        public string CancelDelivery(int deliveryID) {
            return base.Channel.CancelDelivery(deliveryID);
        }
        
        public System.Threading.Tasks.Task<string> CancelDeliveryAsync(int deliveryID) {
            return base.Channel.CancelDeliveryAsync(deliveryID);
        }
        
        public System.Data.DataTable GetAllDeliveryDetails() {
            return base.Channel.GetAllDeliveryDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllDeliveryDetailsAsync() {
            return base.Channel.GetAllDeliveryDetailsAsync();
        }
        
        public string GetDeliveryDetailsByID(int deliveryID) {
            return base.Channel.GetDeliveryDetailsByID(deliveryID);
        }
        
        public System.Threading.Tasks.Task<string> GetDeliveryDetailsByIDAsync(int deliveryID) {
            return base.Channel.GetDeliveryDetailsByIDAsync(deliveryID);
        }
        
        public string UpdatePurchaseOrderStatus(int purchaseOrderID, string status) {
            return base.Channel.UpdatePurchaseOrderStatus(purchaseOrderID, status);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePurchaseOrderStatusAsync(int purchaseOrderID, string status) {
            return base.Channel.UpdatePurchaseOrderStatusAsync(purchaseOrderID, status);
        }
    }
}
