//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techfix.RFQService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RFQ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RFQ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RFQIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescriptionField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryRequirementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PricingFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTermsField;
        
        private System.DateTime ValidityPeriodField;
        
        private System.DateTime RequestDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RFQID {
            get {
                return this.RFQIDField;
            }
            set {
                if ((this.RFQIDField.Equals(value) != true)) {
                    this.RFQIDField = value;
                    this.RaisePropertyChanged("RFQID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescriptionField, value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Specifications {
            get {
                return this.SpecificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationsField, value) != true)) {
                    this.SpecificationsField = value;
                    this.RaisePropertyChanged("Specifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DeliveryRequirements {
            get {
                return this.DeliveryRequirementsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryRequirementsField, value) != true)) {
                    this.DeliveryRequirementsField = value;
                    this.RaisePropertyChanged("DeliveryRequirements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PricingFormat {
            get {
                return this.PricingFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.PricingFormatField, value) != true)) {
                    this.PricingFormatField = value;
                    this.RaisePropertyChanged("PricingFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PaymentTerms {
            get {
                return this.PaymentTermsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTermsField, value) != true)) {
                    this.PaymentTermsField = value;
                    this.RaisePropertyChanged("PaymentTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ValidityPeriod {
            get {
                return this.ValidityPeriodField;
            }
            set {
                if ((this.ValidityPeriodField.Equals(value) != true)) {
                    this.ValidityPeriodField = value;
                    this.RaisePropertyChanged("ValidityPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuotationIDField;
        
        private int RFQIDField;
        
        private int SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        private decimal QuotationAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuotationDetailsField;
        
        private System.DateTime SubmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((this.QuotationIDField.Equals(value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RFQID {
            get {
                return this.RFQIDField;
            }
            set {
                if ((this.RFQIDField.Equals(value) != true)) {
                    this.RFQIDField = value;
                    this.RaisePropertyChanged("RFQID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal QuotationAmount {
            get {
                return this.QuotationAmountField;
            }
            set {
                if ((this.QuotationAmountField.Equals(value) != true)) {
                    this.QuotationAmountField = value;
                    this.RaisePropertyChanged("QuotationAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DeliverySchedule {
            get {
                return this.DeliveryScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryScheduleField, value) != true)) {
                    this.DeliveryScheduleField = value;
                    this.RaisePropertyChanged("DeliverySchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string QuotationDetails {
            get {
                return this.QuotationDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuotationDetailsField, value) != true)) {
                    this.QuotationDetailsField = value;
                    this.RaisePropertyChanged("QuotationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime SubmissionDate {
            get {
                return this.SubmissionDateField;
            }
            set {
                if ((this.SubmissionDateField.Equals(value) != true)) {
                    this.SubmissionDateField = value;
                    this.RaisePropertyChanged("SubmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RFQService.RFQServiceSoap")]
    public interface RFQServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllRFQsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRFQs", ReplyAction="*")]
        Techfix.RFQService.GetAllRFQsResponse GetAllRFQs(Techfix.RFQService.GetAllRFQsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRFQs", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.RFQService.GetAllRFQsResponse> GetAllRFQsAsync(Techfix.RFQService.GetAllRFQsRequest request);
        
        // CODEGEN: Generating message contract since element name productDescription from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManageRFQ", ReplyAction="*")]
        Techfix.RFQService.ManageRFQResponse ManageRFQ(Techfix.RFQService.ManageRFQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManageRFQ", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.RFQService.ManageRFQResponse> ManageRFQAsync(Techfix.RFQService.ManageRFQRequest request);
        
        // CODEGEN: Generating message contract since element name GetRFQByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRFQByID", ReplyAction="*")]
        Techfix.RFQService.GetRFQByIDResponse GetRFQByID(Techfix.RFQService.GetRFQByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRFQByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.RFQService.GetRFQByIDResponse> GetRFQByIDAsync(Techfix.RFQService.GetRFQByIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuotationsByRFQIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuotationsByRFQID", ReplyAction="*")]
        Techfix.RFQService.GetQuotationsByRFQIDResponse GetQuotationsByRFQID(Techfix.RFQService.GetQuotationsByRFQIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuotationsByRFQID", ReplyAction="*")]
        System.Threading.Tasks.Task<Techfix.RFQService.GetQuotationsByRFQIDResponse> GetQuotationsByRFQIDAsync(Techfix.RFQService.GetQuotationsByRFQIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRFQ", ReplyAction="*")]
        bool DeleteRFQ(int rfqID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRFQ", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteRFQAsync(int rfqID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRFQsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRFQs", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetAllRFQsRequestBody Body;
        
        public GetAllRFQsRequest() {
        }
        
        public GetAllRFQsRequest(Techfix.RFQService.GetAllRFQsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRFQsRequestBody {
        
        public GetAllRFQsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRFQsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRFQsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetAllRFQsResponseBody Body;
        
        public GetAllRFQsResponse() {
        }
        
        public GetAllRFQsResponse(Techfix.RFQService.GetAllRFQsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRFQsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.RFQService.RFQ[] GetAllRFQsResult;
        
        public GetAllRFQsResponseBody() {
        }
        
        public GetAllRFQsResponseBody(Techfix.RFQService.RFQ[] GetAllRFQsResult) {
            this.GetAllRFQsResult = GetAllRFQsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ManageRFQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ManageRFQ", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.ManageRFQRequestBody Body;
        
        public ManageRFQRequest() {
        }
        
        public ManageRFQRequest(Techfix.RFQService.ManageRFQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ManageRFQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rfqID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string specifications;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string deliveryRequirements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pricingFormat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string paymentTerms;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime validityPeriod;
        
        public ManageRFQRequestBody() {
        }
        
        public ManageRFQRequestBody(int rfqID, string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            this.rfqID = rfqID;
            this.productDescription = productDescription;
            this.quantity = quantity;
            this.specifications = specifications;
            this.deliveryRequirements = deliveryRequirements;
            this.pricingFormat = pricingFormat;
            this.paymentTerms = paymentTerms;
            this.validityPeriod = validityPeriod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ManageRFQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ManageRFQResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.ManageRFQResponseBody Body;
        
        public ManageRFQResponse() {
        }
        
        public ManageRFQResponse(Techfix.RFQService.ManageRFQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ManageRFQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ManageRFQResult;
        
        public ManageRFQResponseBody() {
        }
        
        public ManageRFQResponseBody(string ManageRFQResult) {
            this.ManageRFQResult = ManageRFQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRFQByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRFQByID", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetRFQByIDRequestBody Body;
        
        public GetRFQByIDRequest() {
        }
        
        public GetRFQByIDRequest(Techfix.RFQService.GetRFQByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRFQByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rfqID;
        
        public GetRFQByIDRequestBody() {
        }
        
        public GetRFQByIDRequestBody(int rfqID) {
            this.rfqID = rfqID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRFQByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRFQByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetRFQByIDResponseBody Body;
        
        public GetRFQByIDResponse() {
        }
        
        public GetRFQByIDResponse(Techfix.RFQService.GetRFQByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRFQByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.RFQService.RFQ GetRFQByIDResult;
        
        public GetRFQByIDResponseBody() {
        }
        
        public GetRFQByIDResponseBody(Techfix.RFQService.RFQ GetRFQByIDResult) {
            this.GetRFQByIDResult = GetRFQByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuotationsByRFQIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuotationsByRFQID", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetQuotationsByRFQIDRequestBody Body;
        
        public GetQuotationsByRFQIDRequest() {
        }
        
        public GetQuotationsByRFQIDRequest(Techfix.RFQService.GetQuotationsByRFQIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuotationsByRFQIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rfqID;
        
        public GetQuotationsByRFQIDRequestBody() {
        }
        
        public GetQuotationsByRFQIDRequestBody(int rfqID) {
            this.rfqID = rfqID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuotationsByRFQIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuotationsByRFQIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Techfix.RFQService.GetQuotationsByRFQIDResponseBody Body;
        
        public GetQuotationsByRFQIDResponse() {
        }
        
        public GetQuotationsByRFQIDResponse(Techfix.RFQService.GetQuotationsByRFQIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuotationsByRFQIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Techfix.RFQService.Quotation[] GetQuotationsByRFQIDResult;
        
        public GetQuotationsByRFQIDResponseBody() {
        }
        
        public GetQuotationsByRFQIDResponseBody(Techfix.RFQService.Quotation[] GetQuotationsByRFQIDResult) {
            this.GetQuotationsByRFQIDResult = GetQuotationsByRFQIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RFQServiceSoapChannel : Techfix.RFQService.RFQServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RFQServiceSoapClient : System.ServiceModel.ClientBase<Techfix.RFQService.RFQServiceSoap>, Techfix.RFQService.RFQServiceSoap {
        
        public RFQServiceSoapClient() {
        }
        
        public RFQServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RFQServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RFQServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RFQServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.RFQService.GetAllRFQsResponse Techfix.RFQService.RFQServiceSoap.GetAllRFQs(Techfix.RFQService.GetAllRFQsRequest request) {
            return base.Channel.GetAllRFQs(request);
        }
        
        public Techfix.RFQService.RFQ[] GetAllRFQs() {
            Techfix.RFQService.GetAllRFQsRequest inValue = new Techfix.RFQService.GetAllRFQsRequest();
            inValue.Body = new Techfix.RFQService.GetAllRFQsRequestBody();
            Techfix.RFQService.GetAllRFQsResponse retVal = ((Techfix.RFQService.RFQServiceSoap)(this)).GetAllRFQs(inValue);
            return retVal.Body.GetAllRFQsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.RFQService.GetAllRFQsResponse> Techfix.RFQService.RFQServiceSoap.GetAllRFQsAsync(Techfix.RFQService.GetAllRFQsRequest request) {
            return base.Channel.GetAllRFQsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.RFQService.GetAllRFQsResponse> GetAllRFQsAsync() {
            Techfix.RFQService.GetAllRFQsRequest inValue = new Techfix.RFQService.GetAllRFQsRequest();
            inValue.Body = new Techfix.RFQService.GetAllRFQsRequestBody();
            return ((Techfix.RFQService.RFQServiceSoap)(this)).GetAllRFQsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.RFQService.ManageRFQResponse Techfix.RFQService.RFQServiceSoap.ManageRFQ(Techfix.RFQService.ManageRFQRequest request) {
            return base.Channel.ManageRFQ(request);
        }
        
        public string ManageRFQ(int rfqID, string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            Techfix.RFQService.ManageRFQRequest inValue = new Techfix.RFQService.ManageRFQRequest();
            inValue.Body = new Techfix.RFQService.ManageRFQRequestBody();
            inValue.Body.rfqID = rfqID;
            inValue.Body.productDescription = productDescription;
            inValue.Body.quantity = quantity;
            inValue.Body.specifications = specifications;
            inValue.Body.deliveryRequirements = deliveryRequirements;
            inValue.Body.pricingFormat = pricingFormat;
            inValue.Body.paymentTerms = paymentTerms;
            inValue.Body.validityPeriod = validityPeriod;
            Techfix.RFQService.ManageRFQResponse retVal = ((Techfix.RFQService.RFQServiceSoap)(this)).ManageRFQ(inValue);
            return retVal.Body.ManageRFQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.RFQService.ManageRFQResponse> Techfix.RFQService.RFQServiceSoap.ManageRFQAsync(Techfix.RFQService.ManageRFQRequest request) {
            return base.Channel.ManageRFQAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.RFQService.ManageRFQResponse> ManageRFQAsync(int rfqID, string productDescription, int quantity, string specifications, string deliveryRequirements, string pricingFormat, string paymentTerms, System.DateTime validityPeriod) {
            Techfix.RFQService.ManageRFQRequest inValue = new Techfix.RFQService.ManageRFQRequest();
            inValue.Body = new Techfix.RFQService.ManageRFQRequestBody();
            inValue.Body.rfqID = rfqID;
            inValue.Body.productDescription = productDescription;
            inValue.Body.quantity = quantity;
            inValue.Body.specifications = specifications;
            inValue.Body.deliveryRequirements = deliveryRequirements;
            inValue.Body.pricingFormat = pricingFormat;
            inValue.Body.paymentTerms = paymentTerms;
            inValue.Body.validityPeriod = validityPeriod;
            return ((Techfix.RFQService.RFQServiceSoap)(this)).ManageRFQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.RFQService.GetRFQByIDResponse Techfix.RFQService.RFQServiceSoap.GetRFQByID(Techfix.RFQService.GetRFQByIDRequest request) {
            return base.Channel.GetRFQByID(request);
        }
        
        public Techfix.RFQService.RFQ GetRFQByID(int rfqID) {
            Techfix.RFQService.GetRFQByIDRequest inValue = new Techfix.RFQService.GetRFQByIDRequest();
            inValue.Body = new Techfix.RFQService.GetRFQByIDRequestBody();
            inValue.Body.rfqID = rfqID;
            Techfix.RFQService.GetRFQByIDResponse retVal = ((Techfix.RFQService.RFQServiceSoap)(this)).GetRFQByID(inValue);
            return retVal.Body.GetRFQByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.RFQService.GetRFQByIDResponse> Techfix.RFQService.RFQServiceSoap.GetRFQByIDAsync(Techfix.RFQService.GetRFQByIDRequest request) {
            return base.Channel.GetRFQByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.RFQService.GetRFQByIDResponse> GetRFQByIDAsync(int rfqID) {
            Techfix.RFQService.GetRFQByIDRequest inValue = new Techfix.RFQService.GetRFQByIDRequest();
            inValue.Body = new Techfix.RFQService.GetRFQByIDRequestBody();
            inValue.Body.rfqID = rfqID;
            return ((Techfix.RFQService.RFQServiceSoap)(this)).GetRFQByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Techfix.RFQService.GetQuotationsByRFQIDResponse Techfix.RFQService.RFQServiceSoap.GetQuotationsByRFQID(Techfix.RFQService.GetQuotationsByRFQIDRequest request) {
            return base.Channel.GetQuotationsByRFQID(request);
        }
        
        public Techfix.RFQService.Quotation[] GetQuotationsByRFQID(int rfqID) {
            Techfix.RFQService.GetQuotationsByRFQIDRequest inValue = new Techfix.RFQService.GetQuotationsByRFQIDRequest();
            inValue.Body = new Techfix.RFQService.GetQuotationsByRFQIDRequestBody();
            inValue.Body.rfqID = rfqID;
            Techfix.RFQService.GetQuotationsByRFQIDResponse retVal = ((Techfix.RFQService.RFQServiceSoap)(this)).GetQuotationsByRFQID(inValue);
            return retVal.Body.GetQuotationsByRFQIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Techfix.RFQService.GetQuotationsByRFQIDResponse> Techfix.RFQService.RFQServiceSoap.GetQuotationsByRFQIDAsync(Techfix.RFQService.GetQuotationsByRFQIDRequest request) {
            return base.Channel.GetQuotationsByRFQIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Techfix.RFQService.GetQuotationsByRFQIDResponse> GetQuotationsByRFQIDAsync(int rfqID) {
            Techfix.RFQService.GetQuotationsByRFQIDRequest inValue = new Techfix.RFQService.GetQuotationsByRFQIDRequest();
            inValue.Body = new Techfix.RFQService.GetQuotationsByRFQIDRequestBody();
            inValue.Body.rfqID = rfqID;
            return ((Techfix.RFQService.RFQServiceSoap)(this)).GetQuotationsByRFQIDAsync(inValue);
        }
        
        public bool DeleteRFQ(int rfqID) {
            return base.Channel.DeleteRFQ(rfqID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRFQAsync(int rfqID) {
            return base.Channel.DeleteRFQAsync(rfqID);
        }
    }
}
